---
title: "Sensitivity demo"
output: html_document
---

```{r pkgs, message = FALSE}
library("deSolve")
library("bbmle")
source("../R/fitSIR_funs.R")
```

I'm going to show how to use the sensitivity functions...

## Gradient function

I'm going to claim that this is the correct sensitivity equation:

$$
\begin{aligned}
\frac{\partial}{\partial t}\frac{\partial I(t,\theta)}{\partial\theta} &= \frac{\partial f_I}{\partial\theta}\\
&= \frac{\partial f_I}{\partial S}\frac{\partial  S}{\partial\theta} + \frac{\partial f_I}{\partial I}\frac{\partial I}{\partial\theta} + \frac{\partial f_I}{\partial\theta} \\
\end{aligned}
$$

## Example 

```{r ex.sim}
tvec <- seq(1, 60, 0.2)

pars <- c(beta = 0.5,
	gamma = 0.1,
	N= 501,
	i0 = 0.01)

pars2 <- c(beta = 0.55,
	gamma = 0.1,
	N= 501,
	i0 = 0.01)

a = SIR.detsim(tvec, pars, findSens = TRUE)

a2 = SIR.detsim(tvec, pars2, findSens = TRUE)

z = (a2$I-a$I)/0.05

plot(a$I, type = "l")
lines(a2$I, col = "2")

plot(z, type = "l", ylim = c(-500, 1000))

lines(a$nu_beta_I, col = 2)

lines(a2$nu_beta_I, col = 3)

```

## SSQ example

```{r ssq.ex}
fake.obs = a[,c("time", "I")]
names(fake.obs) = c("tvec", "count")

pars3 <- c(beta = 0.51,
	gamma = 0.10,
	N= 501,
	i0 = 0.01)

pars4 <- c(beta = 0.501,
	gamma = 0.10,
	N= 501,
	i0 = 0.01)

findSens(fake.obs, pars3)
findSens(fake.obs, pars4)

```

## Bombay example - initial values

We start with these three equations:

$$
\begin{aligned}
r &= \beta - \gamma,\\
-\frac{Q}{I_p} &= \frac{\beta\gamma}{N},\\
N - I_0 - \int I(t) dt = \frac{\gamma}{\beta}N,
\end{aligned}
$$

where $I(t)$ is incidence. Substition gives us following two equations:

$$
\begin{aligned}
N &= - \gamma^2 \frac{I_p}{Q} + I_0 + \int I(t) dt\\
N &= - (\gamma+r) \gamma \frac{I_p}{Q}
\end{aligned}
$$

This gives

$$
\begin{aligned}
(\gamma+r) \gamma \frac{I_p}{Q} &= \gamma^2 \frac{I_p}{Q} - I_0 - \int I(t) dt\\
\gamma^2 \frac{I_p}{Q} + r \gamma \frac{I_p}{Q} &= \gamma^2 \frac{I_p}{Q} - I_0 - \int I(t) dt\\
r \gamma \frac{I_p}{Q} &=- (I_0 + \int I(t) dt)\\
\end{aligned}
$$

```{r}
library("fitsir")

bombay2 <- setNames(bombay,c("tvec","count"))

iniP.ex <- trans.pars(startfun(data=bombay2, auto = TRUE))

findSens(bombay2, iniP.ex, plot.it = TRUE)

fitP <- coef(fitsir(bombay2, start = startfun(data=bombay2, auto = TRUE)))

findSens(bombay2, trans.pars(fitP), plot.it = TRUE)

```

