---
title: "Manuscript outline/draft"
author: Ben Bolker, Sang Woo Park, David Earn
date: "`r format(Sys.time(), '%H:%M %d %B %Y')`"
output: html_document
bibliography: fitsir_ms.bib
---

## Introduction

The general goal is a *brief* (if possible) pedagogically oriented paper,
aimed at biomathematicians/students coming for the first time to the
idea of fitting curves to epidemic models. Without going too deeply
into any one area (likelihood theory, optimization, ...), we aim to
provide a primer and pitfall-avoidance guide for fits of simple ODE
models (focusing particularly on SIR models) to epidemic data.

- model fitting and inference on stochastic dynamical systems is a surprisingly difficult topic, drawing on areas from nonlinear optimization to maximum likelihood estimation. We will touch on a broad

- treat the problem as though all parameters are unknown. Maybe unrealistic: cf. 

## Methods

- ODE implementation
   - R vs C
   - integrators (RK4 vs LSODA)
- starting conditions
   - auto-start
   - LHS
- optimization
   - different optimizers?
   - finite-diff vs sensitivity equations
   - restarting from best fit

## Results

- second figure from `fitLHS_explore` (what are the differences among the models?)
- geometry of likelihood surface


## Results

- Two scales of local minima: large and small
- Large:
   - interesting (we know there are lots of problems with local minima in nonlinear fits: cf Ripley, Roodman, Etienne et al, Bolker 2008, Raue et al)
   - possibly practical, e.g. if knowing very little about the system/not eyeballing
- Small:
   - is it real or is it numerics? How do we tell?
   - does it matter - are there many minima but all are within any reasonable confidence region
   - parameter range can be very wide, but is this just an indication of how unstable/unidentifiable the problem is when we try to estimate everything at once?

## Potential topics (mostly for discussion)

- **trajectory-matching vs. gradient-matching**; what's the difference? when does it matter? (this paper will focus on trajectory matching) [@ellner_fitting_2002;@bolker_ecological_2008]
- **early-epidemic vs whole-epidemic**: lots of work on fitting early epidemics, e.g. @chowell_comparative_2007, @ma_estimating_2014 ; that's not what we're doing here ... also, we're only going to discuss general principles here, focus on simple SIR (maybe comment on SEIR), but not worry about extensions (waning immunity, Ebola/funeral-transmission ... etc.)
- **prevalence vs. incidence**: need to distinguish these cases (typical cases will involve incidence data). Comment on pitfalls of cumulative-incidence approaches (Chowell) without appropriate corrections (maybe discussed elsewhere? @king_avoidable_2015 ?)
- **least-squares vs. likelihood formulations**: equivalence of least-squares and likelihood approaches; advantages of likelihood in providing a framework for inference (confidence intervals). Mention Wald vs likelihood profile CIs.
- **optimization issues**: multiple maxima (if they exist?); ridges [@polansky_likelihood_2009]. Optimization frameworks (e.g. Nelder-Mead vs quasi-Newton); sensitivity equations [@raue_lessons_2013]. Starting points (auto-start methods)
- **identifiability/estimability issues**: (still in progress!) expected difficulties in optimization, especially with vague starting points. Something about solutions ... fixing parameters (with attendant dangers; @elderd_uncertainty_2006). Bayesian priors, bounds ... ?
- **advanced methods**: *brief* pointers to relevant literature here. Dealing with combined process/measurement error [@king_avoidable_2015]; iterated filtering, TSIR, etc.. Bayesian methods (Stan, `debInfer`, ...)

## To do

- convert document to `.Rnw` format?
- what shall we use as a case study? sims; but also some real data set (pref. *not* Bombay data set, because of @bacaer_model_2012 ...)

## References
