---
title: "Profiling"
output: html_document
---

```{r pkgs,echo=FALSE,message=FALSE}
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2); theme_set(theme_bw())
library(devtools)
load_all("..")
```
```{r load, echo = FALSE}
fn <- "fitLHS.rda"
fn2 <- "fitLHS2.rda"
fn3 <- "fitLHS3.rda"
fn4 <- "fitLHS4.rda"
## L2 uses L1 as starting values to fit the curve
## L3 uses fitsir.optim based on nll sensitivity
## L4 is like L2 but it uses L3 as starting values
L1 <- load(fn)  ## contains p (starting values), [fs]{pars,.nll,.SSQ}
L2 <- load(fn2)
L3 <- load(fn3) ## npars, n.nll, n.SSQ
L4 <- load(fn4) ## npars2, n.nll2, n.SSQ2
```

We're going to use `fitsir.optim(nll = TRUE)` for now. Let's sort out the good parameters first:

```{r}
bombay2 <- setNames(bombay, c("tvec", "count"))
spars.good2 <- spars[(s.nll < 167.7),]
s.nll.good2 <- s.nll[(s.nll < 167.7)]
s.nll.good2 <- s.nll.good2[!is.na(s.nll.good2)]
spars.good2 <- spars.good2[!is.na(s.nll.good2),]

min.ind <- which.min(s.nll.good2)
min.pars <- as.numeric(spars.good2[min.ind,])
names(min.pars) <- c("log.beta", "log.gamma", "log.N", "logit.i")
```

Here's a function for 2 parameter optimization:

```{r}
fitsir.optim2 <- function(data,
                         start = startfun(),
                         control=list(maxit=1e5),
                         fix.name = c("log.N", "logit.i")){
    
    name <- c("log.beta", "log.gamma", "log.N", "logit.i")
    
    target.name <- name[which(!(name %in% fix.name))]
    
    fix <- start[fix.name]
    
    start.par <- start[target.name]
    
    f.env <- new.env()
    ## set initial values
    assign("oldval",NULL,f.env)
    assign("oldpar",NULL,f.env)
    assign("oldgrad",NULL,f.env)
    assign("data", data, f.env)
    objfun <- function(par) {
        if (identical(par,oldpar)) {
            return(oldval)
        }
        
        test.pars <- setNames(rep(NA,4), name)
        test.pars[fix.name] <- fix
        test.pars[target.name] <- par
        
        v <- findSens(data, test.pars, nll = TRUE)
        oldval <<- v["val"]
        oldgrad <<- v[2:3]
        oldpar <<- par
        
        return(oldval)
    }
    attr(objfun, "parnames") <- target.name
    environment(objfun) <- f.env
    gradfun <- function(par) {
        if (identical(par,oldpar)) {
            return(oldgrad)
        }
        
        test.pars <- setNames(rep(NA,4), name)
        test.pars[fix.name] <- fix
        test.pars[target.name] <- par
        
        v <- findSens(data, test.pars, nll = TRUE)
        oldval <<- v["val"]
        oldgrad <<- v[2:3]
        oldpar <<- par
        return(oldgrad)
    }
    environment(gradfun) <- f.env
    
    
    m <- mle2(objfun,
              vecpar=TRUE,
              start=start.par,
              method="BFGS",
              control=control,
              gr = gradfun,
              data=c(data,list(debug=debug)))
    
    return(m)
}
```

Trying...:

```{r }
library(emdbook)

tmpfun <- function(x, y, basepars = min.pars,
                   fix.name = c("log.N", "logit.i")){
    pars <- basepars
    pars[fix.name] <- c(x, y)
    
    m <- fitsir.optim2(bombay2, start = pars, fix.name = fix.name)
    return(c(logLik(m)))
}


fn <- "profile.rda"
if (file.exists(fn)) {
    load(fn)
} else {
    beta.gamma <- curve3d(tmpfun(x, y, fix.name = c("log.beta", "log.gamma")),
            xlim = min.pars["log.beta"]* c(0.8, 1.2),
            ylim = min.pars["log.gamma"] * c(0.8, 1.2),
            n = c(31,31))
    
    beta.N <- curve3d(tmpfun(x, y, fix.name = c("log.beta", "log.N")),
            xlim = min.pars["log.beta"]* c(0.8, 1.2),
            ylim = min.pars["log.N"] * c(0.8, 1.2),
            n = c(31,31))
    
    beta.i <- curve3d(tmpfun(x, y, fix.name = c("log.beta", "logit.i")),
            xlim = min.pars["log.beta"]* c(0.8, 1.2),
            ylim = min.pars["logit.i"] * c(1.2, 0.8),
            n = c(31,31))
    
    gamma.N <- curve3d(tmpfun(x, y, fix.name = c("log.gamma", "log.N")),
            xlim = min.pars["log.gamma"]* c(0.8, 1.2),
            ylim = min.pars["log.N"] * c(0.8, 1.2),
            n = c(31,31))
    
    gamma.i <- curve3d(tmpfun(x, y, fix.name = c("log.gamma", "logit.i")),
            xlim = min.pars["log.gamma"]* c(0.8, 1.2),
            ylim = min.pars["logit.i"] * c(1.2, 0.8),
            n = c(31,31))
    
    N.i <- curve3d(tmpfun(x, y, fix.name = c("log.N", "logit.i")),
            xlim = min.pars["log.N"]* c(0.80, 1.2),
            ylim = min.pars["logit.i"] * c(1.2, 0.8),
            n = c(31,31))
    
    save("beta.gamma", "beta.N", "beta.i", "gamma.N", "gamma.i", "N.i", file=fn)
}

resList <- list(beta.gamma, beta.N, beta.i, gamma.N, gamma.i, N.i)
resName <- c("beta.gamma", "beta.N", "beta.i", "gamma.N", "gamma.i", "N.i")
resList <- setNames(resList, resName)


l <- lapply(resName, FUN = function(name){
    
    L <- resList[[name]]
    
    n <- strsplit(name, split = "[.]")[[1]]
    
    with(L,{
        image(x,y,z, xlab = n[1], ylab = n[2])
    })
})

```
